name: Dependency Scanning for Snyk and Trivy (Ruby)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk-scan:
    name: Snyk Dependency Scan for Ruby
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # Set to your project's Ruby version

      - name: Install Bundler
        run: gem install bundler

      - name: Check if Gemfile exists
        run: |
          if [ ! -f Gemfile ]; then
            echo "Gemfile not found, exiting.";
            exit 1;
          fi

      - name: Install dependencies
        run: bundle install

      - name: Install Snyk CLI
        run: npm install -g snyk # Install Snyk globally

      - name: Authenticate Snyk
        run: snyk auth "${{ secrets.SNYK_TOKEN_3 }}" # Use your SNYK_TOKEN secret

      - name: Run Snyk to check for vulnerabilities
        run: snyk test --severity-threshold=medium

      - name: Monitor project in Snyk
        run: snyk monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN_3 }}

  trivy-scan:
    name: Trivy Filesystem Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.35.0/trivy_0.35.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.35.0_Linux-64bit.deb

      - name: Cache Trivy DB
        uses: actions/cache@v3
        with:
          path: ~/.cache/trivy
          key: trivy-db-${{ runner.os }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            trivy-db-${{ runner.os }}-

      - name: Check if Gemfile.lock exists
        run: |
          if [ ! -f Gemfile.lock ]; then
            echo "Gemfile.lock not found, exiting.";
            exit 1;
          fi

      - name: Run Trivy Filesystem Scan (for Ruby dependencies)
        run: |
          # Running Trivy scan on Gemfile directory
          trivy fs --exit-code 1 --severity HIGH,CRITICAL .